apiVersion: v1
kind: Service
metadata:
  name: queue
spec:
  selector: 
    app: queue
  
  ports:
    - name: admin
      port: 8161
      nodePort: 30010
    
    - name: endpoint
      port: 61616
  
  type: NodePort