apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector: 
    app: queue
  
  ports:
    - name: admin
      port: 8161
      nodePort: 30011
    
    - name: endpoint
      port: 61616
  
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: position-tracker
  
  ports:
    - name: 
      port: 8080

  type: ClusterIP